package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Apostas generated by hbm2java
 */
@Entity
@Table(name="apostas"
)
public class Apostas  implements java.io.Serializable {


     private int idAposta;
     private Mercados mercados;
     private String descricao;
     private Integer ordem;
     private Set<Runner> runners = new HashSet<Runner>(0);

    public Apostas() {
    }

	
    public Apostas(int idAposta, Mercados mercados) {
        this.idAposta = idAposta;
        this.mercados = mercados;
    }
    public Apostas(int idAposta, Mercados mercados, String descricao, Integer ordem, Set<Runner> runners) {
       this.idAposta = idAposta;
       this.mercados = mercados;
       this.descricao = descricao;
       this.ordem = ordem;
       this.runners = runners;
    }
   
     @Id 
    
    @Column(name="idAposta", unique=true, nullable=false)
    public int getIdAposta() {
        return this.idAposta;
    }
    
    public void setIdAposta(int idAposta) {
        this.idAposta = idAposta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMercado", nullable=false)
    public Mercados getMercados() {
        return this.mercados;
    }
    
    public void setMercados(Mercados mercados) {
        this.mercados = mercados;
    }
    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name="ordem")
    public Integer getOrdem() {
        return this.ordem;
    }
    
    public void setOrdem(Integer ordem) {
        this.ordem = ordem;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="apostas")
    public Set<Runner> getRunners() {
        return this.runners;
    }
    
    public void setRunners(Set<Runner> runners) {
        this.runners = runners;
    }




}


