package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Classificacao generated by hbm2java
 */
@Entity
@Table(name="classificacao"
)
public class Classificacao  implements java.io.Serializable {


     private int idclassificacao;
     private Equipa equipa;
     private EpocaLiga epocaLiga;
     private Date dataAct;
     private int golosMarcadosCasa;
     private int golosMarcadosFora;
     private int golosSofridosCasa;
     private int golosSofridosFora;
     private int jogosCasa;
     private int jogosFora;
     private int pontos;

    public Classificacao() {
    }

    public Classificacao(int idclassificacao, Equipa equipa, EpocaLiga epocaLiga, Date dataAct, int golosMarcadosCasa, int golosMarcadosFora, int golosSofridosCasa, int golosSofridosFora, int jogosCasa, int jogosFora, int pontos) {
       this.idclassificacao = idclassificacao;
       this.equipa = equipa;
       this.epocaLiga = epocaLiga;
       this.dataAct = dataAct;
       this.golosMarcadosCasa = golosMarcadosCasa;
       this.golosMarcadosFora = golosMarcadosFora;
       this.golosSofridosCasa = golosSofridosCasa;
       this.golosSofridosFora = golosSofridosFora;
       this.jogosCasa = jogosCasa;
       this.jogosFora = jogosFora;
       this.pontos = pontos;
    }
   
     @Id 
    
    @Column(name="idclassificacao", unique=true, nullable=false)
    public int getIdclassificacao() {
        return this.idclassificacao;
    }
    
    public void setIdclassificacao(int idclassificacao) {
        this.idclassificacao = idclassificacao;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEquipa", nullable=false)
    public Equipa getEquipa() {
        return this.equipa;
    }
    
    public void setEquipa(Equipa equipa) {
        this.equipa = equipa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEpoca_Liga", nullable=false)
    public EpocaLiga getEpocaLiga() {
        return this.epocaLiga;
    }
    
    public void setEpocaLiga(EpocaLiga epocaLiga) {
        this.epocaLiga = epocaLiga;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_act", nullable=false, length=19)
    public Date getDataAct() {
        return this.dataAct;
    }
    
    public void setDataAct(Date dataAct) {
        this.dataAct = dataAct;
    }
    
    @Column(name="golos_marcados_casa", nullable=false)
    public int getGolosMarcadosCasa() {
        return this.golosMarcadosCasa;
    }
    
    public void setGolosMarcadosCasa(int golosMarcadosCasa) {
        this.golosMarcadosCasa = golosMarcadosCasa;
    }
    
    @Column(name="golos_marcados_fora", nullable=false)
    public int getGolosMarcadosFora() {
        return this.golosMarcadosFora;
    }
    
    public void setGolosMarcadosFora(int golosMarcadosFora) {
        this.golosMarcadosFora = golosMarcadosFora;
    }
    
    @Column(name="golos_sofridos_casa", nullable=false)
    public int getGolosSofridosCasa() {
        return this.golosSofridosCasa;
    }
    
    public void setGolosSofridosCasa(int golosSofridosCasa) {
        this.golosSofridosCasa = golosSofridosCasa;
    }
    
    @Column(name="golos_sofridos_fora", nullable=false)
    public int getGolosSofridosFora() {
        return this.golosSofridosFora;
    }
    
    public void setGolosSofridosFora(int golosSofridosFora) {
        this.golosSofridosFora = golosSofridosFora;
    }
    
    @Column(name="jogos_casa", nullable=false)
    public int getJogosCasa() {
        return this.jogosCasa;
    }
    
    public void setJogosCasa(int jogosCasa) {
        this.jogosCasa = jogosCasa;
    }
    
    @Column(name="jogos_fora", nullable=false)
    public int getJogosFora() {
        return this.jogosFora;
    }
    
    public void setJogosFora(int jogosFora) {
        this.jogosFora = jogosFora;
    }
    
    @Column(name="pontos", nullable=false)
    public int getPontos() {
        return this.pontos;
    }
    
    public void setPontos(int pontos) {
        this.pontos = pontos;
    }




}


