package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Epoca generated by hbm2java
 */
@Entity
@Table(name="epoca"
)
public class Epoca  implements java.io.Serializable {


     private int idEpoca;
     private String epoca;
     private Set<EpocaLiga> epocaLigas = new HashSet<EpocaLiga>(0);

    public Epoca() {
    }

	
    public Epoca(int idEpoca) {
        this.idEpoca = idEpoca;
    }
    public Epoca(int idEpoca, String epoca, Set<EpocaLiga> epocaLigas) {
       this.idEpoca = idEpoca;
       this.epoca = epoca;
       this.epocaLigas = epocaLigas;
    }
   
     @Id 
    
    @Column(name="idEpoca", unique=true, nullable=false)
    public int getIdEpoca() {
        return this.idEpoca;
    }
    
    public void setIdEpoca(int idEpoca) {
        this.idEpoca = idEpoca;
    }
    
    @Column(name="epoca", length=45)
    public String getEpoca() {
        return this.epoca;
    }
    
    public void setEpoca(String epoca) {
        this.epoca = epoca;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="epoca")
    public Set<EpocaLiga> getEpocaLigas() {
        return this.epocaLigas;
    }
    
    public void setEpocaLigas(Set<EpocaLiga> epocaLigas) {
        this.epocaLigas = epocaLigas;
    }




}


