package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpocaLiga generated by hbm2java
 */
@Entity
@Table(name="epoca_liga"
)
public class EpocaLiga  implements java.io.Serializable {


     private int idEpocaLiga;
     private Epoca epoca;
     private Liga liga;
     private Set<Classificacao> classificacaos = new HashSet<Classificacao>(0);
     private Set<Jornada> jornadas = new HashSet<Jornada>(0);

    public EpocaLiga() {
    }

	
    public EpocaLiga(int idEpocaLiga, Epoca epoca, Liga liga) {
        this.idEpocaLiga = idEpocaLiga;
        this.epoca = epoca;
        this.liga = liga;
    }
    public EpocaLiga(int idEpocaLiga, Epoca epoca, Liga liga, Set<Classificacao> classificacaos, Set<Jornada> jornadas) {
       this.idEpocaLiga = idEpocaLiga;
       this.epoca = epoca;
       this.liga = liga;
       this.classificacaos = classificacaos;
       this.jornadas = jornadas;
    }
   
     @Id 
    
    @Column(name="idEpoca_Liga", unique=true, nullable=false)
    public int getIdEpocaLiga() {
        return this.idEpocaLiga;
    }
    
    public void setIdEpocaLiga(int idEpocaLiga) {
        this.idEpocaLiga = idEpocaLiga;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEpoca", nullable=false)
    public Epoca getEpoca() {
        return this.epoca;
    }
    
    public void setEpoca(Epoca epoca) {
        this.epoca = epoca;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLiga", nullable=false)
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="epocaLiga")
    public Set<Classificacao> getClassificacaos() {
        return this.classificacaos;
    }
    
    public void setClassificacaos(Set<Classificacao> classificacaos) {
        this.classificacaos = classificacaos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="epocaLiga")
    public Set<Jornada> getJornadas() {
        return this.jornadas;
    }
    
    public void setJornadas(Set<Jornada> jornadas) {
        this.jornadas = jornadas;
    }




}


