package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipa generated by hbm2java
 */
@Entity
@Table(name="equipa"
)
public class Equipa  implements java.io.Serializable {


     private int idEquipa;
     private String nome;
     private Integer favorita;
     private Set<Jogo> jogosForIdEquipaCasa = new HashSet<Jogo>(0);
     private Set<Classificacao> classificacaos = new HashSet<Classificacao>(0);
     private Set<Jogo> jogosForIdEquipaFora = new HashSet<Jogo>(0);

    public Equipa() {
    }

	
    public Equipa(int idEquipa) {
        this.idEquipa = idEquipa;
    }
    public Equipa(int idEquipa, String nome, Integer favorita, Set<Jogo> jogosForIdEquipaCasa, Set<Classificacao> classificacaos, Set<Jogo> jogosForIdEquipaFora) {
       this.idEquipa = idEquipa;
       this.nome = nome;
       this.favorita = favorita;
       this.jogosForIdEquipaCasa = jogosForIdEquipaCasa;
       this.classificacaos = classificacaos;
       this.jogosForIdEquipaFora = jogosForIdEquipaFora;
    }
   
     @Id 
    
    @Column(name="idEquipa", unique=true, nullable=false)
    public int getIdEquipa() {
        return this.idEquipa;
    }
    
    public void setIdEquipa(int idEquipa) {
        this.idEquipa = idEquipa;
    }
    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="favorita")
    public Integer getFavorita() {
        return this.favorita;
    }
    
    public void setFavorita(Integer favorita) {
        this.favorita = favorita;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipaByIdEquipaCasa")
    public Set<Jogo> getJogosForIdEquipaCasa() {
        return this.jogosForIdEquipaCasa;
    }
    
    public void setJogosForIdEquipaCasa(Set<Jogo> jogosForIdEquipaCasa) {
        this.jogosForIdEquipaCasa = jogosForIdEquipaCasa;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipa")
    public Set<Classificacao> getClassificacaos() {
        return this.classificacaos;
    }
    
    public void setClassificacaos(Set<Classificacao> classificacaos) {
        this.classificacaos = classificacaos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipaByIdEquipaFora")
    public Set<Jogo> getJogosForIdEquipaFora() {
        return this.jogosForIdEquipaFora;
    }
    
    public void setJogosForIdEquipaFora(Set<Jogo> jogosForIdEquipaFora) {
        this.jogosForIdEquipaFora = jogosForIdEquipaFora;
    }




}


