package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Estatisticas generated by hbm2java
 */
@Entity
@Table(name="estatisticas"
)
public class Estatisticas  implements java.io.Serializable {


     private int idEstatisticas;
     private Jogo jogo;
     private int idEquipa;
     private Integer golos;

    public Estatisticas() {
    }

	
    public Estatisticas(int idEstatisticas, Jogo jogo, int idEquipa) {
        this.idEstatisticas = idEstatisticas;
        this.jogo = jogo;
        this.idEquipa = idEquipa;
    }
    public Estatisticas(int idEstatisticas, Jogo jogo, int idEquipa, Integer golos) {
       this.idEstatisticas = idEstatisticas;
       this.jogo = jogo;
       this.idEquipa = idEquipa;
       this.golos = golos;
    }
   
     @Id 
    
    @Column(name="idEstatisticas", unique=true, nullable=false)
    public int getIdEstatisticas() {
        return this.idEstatisticas;
    }
    
    public void setIdEstatisticas(int idEstatisticas) {
        this.idEstatisticas = idEstatisticas;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idJogo", nullable=false)
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
    
    @Column(name="idEquipa", nullable=false)
    public int getIdEquipa() {
        return this.idEquipa;
    }
    
    public void setIdEquipa(int idEquipa) {
        this.idEquipa = idEquipa;
    }
    
    @Column(name="golos")
    public Integer getGolos() {
        return this.golos;
    }
    
    public void setGolos(Integer golos) {
        this.golos = golos;
    }




}


