package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
)
public class Login  implements java.io.Serializable {


     private int idLogin;
     private String username;
     private String password;
     private Integer estado;

    public Login() {
    }

	
    public Login(int idLogin) {
        this.idLogin = idLogin;
    }
    public Login(int idLogin, String username, String password, Integer estado) {
       this.idLogin = idLogin;
       this.username = username;
       this.password = password;
       this.estado = estado;
    }
   
     @Id 
    
    @Column(name="idLogin", unique=true, nullable=false)
    public int getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }
    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


