package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MapeamentoMercados generated by hbm2java
 */
@Entity
@Table(name="mapeamento_mercados"
)
public class MapeamentoMercados  implements java.io.Serializable {


     private Integer idMapMercado;
     private Jogo jogo;
     private Mercados mercados;
     private int marketId;
     private int estado;
     private Set<Runner> runners = new HashSet<Runner>(0);

    public MapeamentoMercados() {
    }

	
    public MapeamentoMercados(Jogo jogo, Mercados mercados, int marketId, int estado) {
        this.jogo = jogo;
        this.mercados = mercados;
        this.marketId = marketId;
        this.estado = estado;
    }
    public MapeamentoMercados(Jogo jogo, Mercados mercados, int marketId, int estado, Set<Runner> runners) {
       this.jogo = jogo;
       this.mercados = mercados;
       this.marketId = marketId;
       this.estado = estado;
       this.runners = runners;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idMap_Mercado", unique=true, nullable=false)
    public Integer getIdMapMercado() {
        return this.idMapMercado;
    }
    
    public void setIdMapMercado(Integer idMapMercado) {
        this.idMapMercado = idMapMercado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idJogo", nullable=false)
    public Jogo getJogo() {
        return this.jogo;
    }
    
    public void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMercado", nullable=false)
    public Mercados getMercados() {
        return this.mercados;
    }
    
    public void setMercados(Mercados mercados) {
        this.mercados = mercados;
    }
    
    @Column(name="marketId", nullable=false)
    public int getMarketId() {
        return this.marketId;
    }
    
    public void setMarketId(int marketId) {
        this.marketId = marketId;
    }
    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mapeamentoMercados")
    public Set<Runner> getRunners() {
        return this.runners;
    }
    
    public void setRunners(Set<Runner> runners) {
        this.runners = runners;
    }




}


