package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mercados generated by hbm2java
 */
@Entity
@Table(name="mercados"
)
public class Mercados  implements java.io.Serializable {


     private int idMercado;
     private String designacao;
     private String mercadoSid;
     private Integer estado;
     private Set<MapeamentoMercados> mapeamentoMercadoses = new HashSet<MapeamentoMercados>(0);
     private Set<Apostas> apostases = new HashSet<Apostas>(0);

    public Mercados() {
    }

	
    public Mercados(int idMercado) {
        this.idMercado = idMercado;
    }
    public Mercados(int idMercado, String designacao, String mercadoSid, Integer estado, Set<MapeamentoMercados> mapeamentoMercadoses, Set<Apostas> apostases) {
       this.idMercado = idMercado;
       this.designacao = designacao;
       this.mercadoSid = mercadoSid;
       this.estado = estado;
       this.mapeamentoMercadoses = mapeamentoMercadoses;
       this.apostases = apostases;
    }
   
     @Id 
    
    @Column(name="idMercado", unique=true, nullable=false)
    public int getIdMercado() {
        return this.idMercado;
    }
    
    public void setIdMercado(int idMercado) {
        this.idMercado = idMercado;
    }
    
    @Column(name="designacao", length=45)
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }
    
    @Column(name="mercado_sid", length=45)
    public String getMercadoSid() {
        return this.mercadoSid;
    }
    
    public void setMercadoSid(String mercadoSid) {
        this.mercadoSid = mercadoSid;
    }
    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mercados")
    public Set<MapeamentoMercados> getMapeamentoMercadoses() {
        return this.mapeamentoMercadoses;
    }
    
    public void setMapeamentoMercadoses(Set<MapeamentoMercados> mapeamentoMercadoses) {
        this.mapeamentoMercadoses = mapeamentoMercadoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mercados")
    public Set<Apostas> getApostases() {
        return this.apostases;
    }
    
    public void setApostases(Set<Apostas> apostases) {
        this.apostases = apostases;
    }




}


