package soccerBet.project.objects;
// Generated 14/Dez/2013 19:38:56 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
)
public class Pais  implements java.io.Serializable {


     private int idPais;
     private String nome;
     private Set<Liga> ligas = new HashSet<Liga>(0);

    public Pais() {
    }

	
    public Pais(int idPais) {
        this.idPais = idPais;
    }
    public Pais(int idPais, String nome, Set<Liga> ligas) {
       this.idPais = idPais;
       this.nome = nome;
       this.ligas = ligas;
    }
   
     @Id 
    
    @Column(name="idPais", unique=true, nullable=false)
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Liga> getLigas() {
        return this.ligas;
    }
    
    public void setLigas(Set<Liga> ligas) {
        this.ligas = ligas;
    }




}


